name: whymake
favicon: null
layout_spectrum: 0
typography_spectrum: 0.37913660728372633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0538136251270771
  lightness: 0.2386272712610662
  saturation: 0.2624184542801231
  rhythmicContrast: 0.0003231868613511324
purpose: []
